// AUTO-GENERATED by scripts/gen-worldmap.mjs — pins for the Contact world map.
export const WORLD_VIEWBOX = "0 0 87 44";
export type WorldPin = { label: string; x: number; y: number; big?: boolean };
export const WORLD_PINS: WorldPin[] = [
  {
    label: "Nashik",
    x: 62.4,
    y: 21.7,
    big: true,
  },
  {
    label: "Patna",
    x: 65,
    y: 20,
  },
  {
    label: "Kharagpur",
    x: 65.4,
    y: 21.1,
  },
  {
    label: "Mumbai",
    x: 62.2,
    y: 21.8,
  },
  {
    label: "Noida",
    x: 63.3,
    y: 19.1,
  },
  {
    label: "Pune",
    x: 62.4,
    y: 22,
  },
  {
    label: "IIT Ropar",
    x: 63.1,
    y: 18.6,
  },
  {
    label: "Shivpuri",
    x: 63.4,
    y: 20,
  },
];
